---
title: "ESM 232 Assignment 5"
author: "Madeline Oliver, Ruoyu Wang, Hannah Garcia"
date: "4/28/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(purrr)
library(deSolve)
library(tinytex)
```

### Use ODE solver
```{r settings.ode, message=FALSE, warning=FALSE}
source("popWithK.R")

# set the initial population to be 1
initialP = 1

# the results will be shown from year 1 to year 50
years = seq(from=1, to=50, by=1)

# set the parameters: base growth rate r and carrying capacity K
parms = list(r = 0.05, K = 20)

# run the solver
Ptime = ode(y=initialP, 
            time=years, 
            func=popWithK,
            parms=parms)

# rename the columns
colnames(Ptime)=c("year","Population")
# attributes(Ptime)

# Check to make sure year 50 is correct
# tail(Ptime)
```

### Graph the results
```{r, message=FALSE, warning=FALSE}
ggplot(as.data.frame(Ptime), aes(year, Population)) +
  geom_point() +
  labs(y="Population", x = "years", title = "Population Growth over 50 Years") +
  theme(plot.title = element_text(hjust = 0.5))
  
```

